channels:
  - plotly
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.3.0=py38_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - bleach=3.1.4=py_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - cffi=1.14.0=py38h2e261b9_0
  - chardet=3.0.4=py38_1003
  - cryptography=2.8=py38h1ba5d50_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - gmp=6.1.2=h6c8ec71_1
  - idna=2.9=py_1
  - importlib_metadata=1.5.0=py38_0
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py38_1
  - jinja2=2.11.2=py_0
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter_client=6.1.2=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.1.0=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - mistune=0.8.4=py38h7b6447c_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - ncurses=6.2=he6710b0_0
  - nodejs=10.13.0=he6710b0_0
  - notebook=6.0.3=py38_0
  - openssl=1.1.1g=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.6.2=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py38_1
  - plotly-orca=1.3.1=1
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - psutil=5.7.0=py38h7b6447c_0
  - ptyprocess=0.6.0=py38_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py38_0
  - pyrsistent=0.16.0=py38h7b6447c_0
  - pysocks=1.7.1=py38_0
  - python=3.8.2=hcf32534_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py38he6710b0_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py38_0
  - send2trash=1.5.0=py38_0
  - setuptools=46.1.3=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h62c20be_1
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py38h7b6447c_1
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alembic==1.4.2
    - appdirs==1.4.3
    - cliff==3.1.0
    - cmaes==0.5.0
    - cmd2==0.8.9
    - colorlog==4.1.0
    - cycler==0.10.0
    - distlib==0.3.0
    - filelock==3.0.12
    - future==0.18.2
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - mako==1.1.2
    - matplotlib==3.2.1
    - numpy==1.18.3
    - optuna==1.3.0
    - pandas==1.0.3
    - pbr==5.4.5
    - plotly==4.6.0
    - prettytable==0.7.2
    - pyparsing==2.4.7
    - pyperclip==1.8.0
    - python-editor==1.0.4
    - pytz==2020.1
    - pyyaml==5.3.1
    - retrying==1.3.3
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - sklearn==0.0
    - sqlalchemy==1.3.16
    - stevedore==1.32.0
    - torch==1.5.0
    - tqdm==4.45.0
    - urllib3==1.25.9
    - virtualenv==20.0.18